spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swift_spring_application
    username: swift_dev
    password: swift
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

server:
  port: 4446

app:
  jwtSecret: w12mJKH2rjS0TVzHu8Vr4tKJqUT9ZotAYNh2NlW0xSIxzrvN0bEVZclvfp73P1sR
  jwtExpiration: 86400000